name: Mono repo

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

stages:
- stage: CheckoutStage

  displayName: 'Checkout and analysis'
  jobs:
  - job: CheckoutJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - script: echo Checkout

    - bash: |
        echo '##vso[task.setvariable variable=UserSyncChanged;isOutput=true;]True'
      displayName: Set changed Files
      name: find_changed_areas

    - bash: |
        echo UserSyncChanged: 
        echo $USERSYNCCHANGED

    - bash: |
        echo find_changed_areas.UserSyncChanged: 
        echo $(find_changed_areas.UserSyncChanged)

- stage: UserSync_DeployStage
  dependsOn: CheckoutStage
  displayName: 'Sync: Stage deploy'
  jobs:
  - job: 'Deploy'
    condition: eq(stageDependencies.CheckoutStage.CheckoutJob.outputs['find_changed_areas.UserSyncChanged'], true)
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo Deployed
